---
language: python
python:
- '2.7'
install:
- 'pip install yamllint==1.8.1'
- 'pip install cfn-lint==0.10.1'
script:
- 'yamllint module.yml'
- 'cfn-lint -t module.yml'
- 'grep -q "LICENSE-2.0" module.yml'
